# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf35e132f831ae6b3abb5c13ef179ad60c28765beb88fcd0924bd30f52f08842c61c3dde09fc79d9f4f743bf07b0c77b30687273cd3caae0086892b36e151b8d

test:
  secret_key_base: 79c1f6dfeb36422c547f72f1a304d65ff8dcc008a44049fa079a6d7ecdb044ddd9d7d8279de0d6558957b6b07cfc7e45a122821ce9047451dc45644bc6ac5391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
